apiVersion: v1
kind: Pod
metadata:
  name: gopher-pod
spec:
  containers:
    - name: gopher-container
      image: inf-repo-registry.cn-wulanchabu.cr.aliyuncs.com/infly-dev/busybox:latest
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
      resources:
        requests:
          gordon.com/gopher: "2"
        limits:
          gordon.com/gopher: "2"